name: Firebase CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: unbuntu-latest
    steps:
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env: 
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}